### ISSUE TITLE
TESmall Could not retrieve index issue

### ISSUE THREAD

**Issue by sanatbhadsavle** [mhammell-laboratory/TEsmall#11]
`[E::idx_find_and_load] Could not retrieve index file for 'Control.multi.bam'`

I get this message when running TESmall on my files. 'Control' being the label name I chose using option `-l`

**Comment by olivertam** [comment]
Hi,

This is a known quirk of the `pysam` module (see [here](https://github.com/pysam-developers/pysam/issues/939). It does not appear to affect the running of `TEsmall`.

Thanks.
