### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file for ...

### ISSUE THREAD

**Issue by slavictoast** [mhammell-laboratory/TEsmall#15]
Dear all,
while using TEsmall, there seems to be an issue with the index files. 
I used 
$ TEsmall -f [inputfile.fq] -i Name
and it seemed to work fine for the first operations but then started to show that there were issues with retrieving index files.
Could you help me to pinpoint the issue here?
Thank you!
Valentina
![TESmall_error](https://user-images.githubusercontent.com/113359113/189663778-7962b0b5-c97b-4794-8dad-15850c5cb2b5.png)

**Comment by olivertam** [comment]
Hi Valentina,

Thank you for your interest in the software.
This is a known quirk of the `pysam` module (see [here](https://github.com/pysam-developers/pysam/issues/939)), and has been reported previously (#11). 
It does not appear to affect the running of `TEsmall`.

Thanks.

**Comment by slavictoast** [comment]
Hi Oliver,
thank you for the quick reply, it worked out fine!
Best regards!
