### ISSUE TITLE
How siRNA is identified？

### ISSUE THREAD

**Issue by LIUXING-bio** [mhammell-laboratory/TEsmall#16]

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Can you elaborate on your question? Are you referring to gene-derived siRNA, or TE-derived siRNA?

In theory, the software identifies small RNA that align to either gene or TE, and consider them small RNA derived from a particular feature (gene/TE). You then need to perform other downstream analyses to truly define them as siRNA (e.g. looking at their distribution along the gene/TE, size profile etc). Thus, while TEsmall will provide you with counts of small RNA derived from particular features, the more strict siRNA definition needs further analyses to confirm.

Thanks.
