### ISSUE TITLE
KeyError: 'piRNA_cluster'

### ISSUE THREAD

**Issue by ra7555ga-s** [mhammell-laboratory/tesmall#2]
Hello,

Thank you so much for this software! I'm excited to try it out with my data. We sequenced a small RNA library with size selection for +30 nt (so no miRNAs or many piRNAs are expected). 

I ran TEsmall with it and I am guessing it finished almost entirely, but an error appeared after 
`INFO Generating summary report...`

The error message:
`Traceback (most recent call last):
  File "/Users/student/anaconda3/envs/tesmall/bin/TEsmall", line 11, in <module>
    load_entry_point('TEsmall==0.4.0', 'console_scripts', 'tesmall')()
  File "/Users/student/anaconda3/envs/tesmall/lib/python2.7/site-packages/TEsmall-0.4.0-py2.7.egg/tesmall/command_line.py", line 76, in main
    gen_summary(args.label, args.order, args.maxaln)
  File "/Users/student/anaconda3/envs/tesmall/lib/python2.7/site-packages/TEsmall-0.4.0-py2.7.egg/tesmall/summary.py", line 401, in gen_summary
    script, div = output_components(p, order, maxaln)
  File "/Users/student/anaconda3/envs/tesmall/lib/python2.7/site-packages/TEsmall-0.4.0-py2.7.egg/tesmall/summary.py", line 317, in output_components
    end = 2*pi*total[ftype]/100
  File "/Users/student/anaconda3/envs/tesmall/lib/python2.7/site-packages/pandas/core/series.py", line 583, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/student/anaconda3/envs/tesmall/lib/python2.7/site-packages/pandas/indexes/base.py", line 1994, in get_value
    raise e1
KeyError: 'piRNA_cluster'`

I am wondering if this is an error expected with the type of experiment we are doing. If so, do you have any guidance towards how to fix it? 

Also, is there a way for the software to start where it left? 

Thank you!

**Comment by wwliao** [comment]
Thanks for your interest in TEsmall.

I guess it's due to no reads were assigned to piRNA_cluster. Does the number is 0 when you do `grep piRNA_cluster *.anno | wc -l`?

Yeah, you can run any step by calling the correspoding function in your Python script.
For example, if you'd like to run the step for generting HTML report, the script should be:

```
from tesmall.summary import gen_summary

gen_summary(prefix, order, maxaln)
```

Could you provide us the command line you used?

Thanks.

**Comment by ra7555ga-s** [comment]
Hello, 

I ran the program as `TEsmall -f <fastq files> -l <labels for the files>` 

The `grep piRNA_cluster *.anno | wc -l`  gave me 82

Thank you!

**Comment by wwliao** [comment]
Then could you check the `*.comp` files to see if there is a piRNA_cluster column?

Thanks.

**Comment by ra7555ga-s** [comment]
Hello,

Sorry for the delay. There is a piRNA_cluster column only in some samples.
The rest of the columns are shared among all (rlen, anti_TE, exon, hairpin, intron, miRNA, sense_TE, structural_RNA).

**Comment by ra7555ga-s** [comment]
The samples that did have the piRNA_cluster column had at least one cell in it greater than zero, so I set the piRNA_cluster column in zeroes for the samples that didn't have it and the report was generated without problem. 

I guess that was the problem, but please let me know if you think its fine. 

Thanks!

**Comment by wwliao** [comment]
Hi,

Yeah, it's totally fine to set the missing piRNA_cluster column to all zeroes. The `.comp` files are derived from the `.anno` files. If no reads are assigned to piRNA_cluster in the `.anno` for a given sample, the corresponding `.comp` file won't have the piRNA_cluster column.

Thanks.
