### ISSUE TITLE
Incorporation of newer human/mouse genome builds?

### ISSUE THREAD

**Issue by juanb001** [mhammell-laboratory/TEsmall#4]
Hi,

First off, thanks for providing all the different TE-related tools; they've been really useful!

I was wondering if there were plans to incorporate native support for the latest human/mouse genome builds (hg38/mm10)? 

Thanks!

**Comment by olivertam** [comment]
Hi,

Sorry for the slow response. We're looking into it now.

Thank you for your patience.

**Comment by juanb001** [comment]
No worries, thanks for looking into it!

**Comment by olivertam** [comment]
Hi,

We are hoping to push a few updates on TEsmall code-base as improvements, but if you want to use the software on the newer genome builds, you can download them [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEsmall/). You should be able to download it into the folder with the other genome files. We may set these new genome builds as default when we update the code.
Let us know if you have trouble using them.

Thanks.

**Comment by juanb001** [comment]
Awesome, thanks for making these builds available. Eager to put this tool to use!

**Comment by juanb001** [comment]
Hi again!

I tried running TEsmall by specifying 'hg38' as the genome, but I get a message saying that 

tesmall: error: argument -g/--genome: invalid choice: 'hg38' (choose from 'dm3', 'mm9', 'hg19')

Is there a way to specify a custom genome? Or would I need to hack the software and temporarily label my 'hg38' genome as 'hg19'?

**Comment by olivertam** [comment]
Hi,

Thanks for pointing this out. I just pushed a small update to Github. Would you mind trying it out and letting me know if it fails?
We will probably do a more thorough fix in the an upcoming release.

Thanks.

**Comment by juanb001** [comment]
I believe it works, thanks!
