### ISSUE TITLE
Singularity as conda replacement for GDPR save HPC environment?

### ISSUE THREAD

**Issue by stela2502** [mhammell-laboratory/TEsmall#5]
Hi,

we have a GDPR save HPC environment and biological software is easiest installed via singularity images instead of being installed into conda environments (no internet on the server).
Can you help with installing your system in a jupyter enabled singularity image?

Thank you!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
We have limited experience with Singularity or Docker images, but we can take a look. We'll let you know if we have some successes.
Thanks.

**Comment by stela2502** [comment]
Hi again,
I have created a fork that basically cripples TEsmall as the plotting lib you use is unavailable for 3.x.
And I could not make python 2.7 work any more.
https://github.com/stela2502/TEsmall_3.x
Probably you could re-add the plotting?

**Comment by olivertam** [comment]
Hi,

Thank you for your efforts in making TEsmall python3-compatible.
Could you let us which modules/plotting commands are broken in python3? We are slowly transitioning our software to python3, and could definitely focus on getting that working as soon as possible.

Thanks.

**Comment by olivertam** [comment]
As a quick followup to your initial question (about Singularity), it looks like the process of containerizing conda environment for Singularity might not be too complicated (see [here](https://stackoverflow.com/questions/54678805/containerize-a-conda-environment-in-a-singularity-container)). While we still need to get python3 compatibility, it might not be too difficult to containerize once that is done.
Thanks.

**Comment by stela2502** [comment]
Hi to make your software python3 compatible I simply used 2to3. The resulting software does almost work.
You had very restrictive software requirements which I loosened up. The software seams to still be able to run.
BUT I had to remove all plotting functionality as the used bokeh library has no charts class any more.
And the version that still has it does not install under python 3. So all you need to do is change the plotting to some other library or port the plots to the new bokeh API.
The containerization is in fact quite simple - as you can see in my github fork.

Great to hear you work on pathon3 compatibility. And I would of cause be proud if you would use any of my suggestions ;-)

**Comment by olivertam** [comment]
Thanks for your suggestions. 
We'll take a look at the Bokeh library and see how to fix the plotting.
All the best.

**Comment by olivertam** [comment]
Hi,

We have made an attempt to update the plotting to use a newer Bokeh library (tested on version 2.2.3). We also implemented your suggestion of using `2to3` to make TEsmall compatible with Python3.
Please note that we have made some other changes (e.g. renaming the tool to `TEsmall`), and so there might be some bugs that we didn't catch. We would recommend a clean re-install to ensure that older versions of the software do not interfere.

Please feel free to try it out, and see if it works for you.
Thanks.
